language: ruby
cache: bundler

os:
  - linux

rvm:
  - jruby
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5

jobs:
  include:
    - os: osx
      osx_image: xcode7.3
      rvm: 1.9.3
    - os: osx
      rvm: 2.0.0
    - os: osx
      rvm: 2.1.0
    - os: osx
      rvm: 2.1.5
    - stage: deploy
      if: branch = master
      os: linux
      rvm: 2.0.0
      deploy:
        provider: rubygems
        gem: travis
        on:
          repo: travis-ci/travis.rb
          ruby: 2.0.0
