language: ruby
cache: bundler

os:
  - linux

rvm:
  - jruby
  
before_install:
  - gem update --system
  - gem --version
  
script:
- bundle exec rake build
- bundle exec rake builddoc

jobs:
  include:
      deploy:
        provider: rubygems
        gem: travis
