language: ruby
cache: bundler

os:
  - linux

rvm:
  - jruby
  
before_install:
  - gem update --system
  - gem --version
  
jobs:
  include:
      deploy:
        provider: rubygems
        gem: travis
