language: ruby
cache: bundler

os:
  - linux

rvm:
  - jruby
  - 2.1.5

jobs:
  include:
      deploy:
        provider: rubygems
        gem: travis
        on:
          repo: travis-ci/travis.rb
          ruby: 2.0.0
